import { ColumnName } from "../generators/names";
import { SQLDatatype, SQLNull } from "../sql-types";
import { SQLTable } from "./table";

interface Props {
  isKey: boolean;
  isNull: boolean;
  name: ColumnName;
  datatype: SQLDatatype;
  autoGenerated: boolean;
}

export interface RefTable {
  table: SQLTable;
  column: SQLColumn;
}

export class SQLColumn {
  readonly autoGenerated: boolean;
  readonly _name: ColumnName;
  private _datatype: SQLDatatype;
  private _isKey: boolean;
  private _isNull: boolean;
  private _unique: boolean;
  private _ref: RefTable | null;

  constructor({ autoGenerated, datatype, isKey, isNull, name }: Props) {
    this._name = name;
    this._datatype = datatype;
    this._isKey = isKey;
    this._isNull = isNull;
    this._unique = false;
    this._ref = null;
    this.autoGenerated = autoGenerated;

    if (datatype instanceof SQLNull) {
      this._isNull = false;
    }
  }

  datatype() {
    return this._datatype;
  }

  setRef(ref: RefTable): void {
    this._ref = ref;
  }

  unique() {
    return this._unique;
  }

  ref() {
    return this._ref;
  }

  equal(other: ColumnName) {
    return this._name.equal(other);
  }

  setIsKey(v: boolean): void {
    this._isKey = v;
  }

  setIsNull(value: boolean) {
    this._isNull = value;
  }

  definition(): string {
    return `${this.datatype().definition()}`;
  }

  isNull() {
    return this._isNull;
  }

  isKey() {
    return this._isKey;
  }

  name() {
    return this._name.value("snake");
  }

  setDatatype(value: SQLDatatype): void {
    this._datatype = value;

    if (value.isGreaterThan(this.datatype())) {
      this._datatype = value;
    }

    if (value instanceof SQLNull) {
      this._isNull = false;
    }
  }

  similar(other: SQLColumn): boolean {
    return other._datatype.isSimilar(this._datatype);
  }
}
